### ISSUE TITLE
Make 'aliases' category in configuration file

### ISSUE THREAD

**Issue by gooddoog** [gooddoog/comproenv#130]
before:
```yaml
alias_0: q qq
alias_1: help h
```
after:
```yaml
aliases:
  global: q qq
  environment: help h
```
